<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventory Report</title>
    <style>
        body { font-family: sans-serif; padding: 20px; }

        /* Header Layout */
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 24px; text-transform: uppercase; }
        .header p { margin: 5px 0; color: #666; }

        /* Table Layout */
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background-color: #eee; text-transform: uppercase; }

        /* Footer/Totals */
        .totals { margin-top: 20px; text-align: right; }
        .totals p { font-size: 14px; font-weight: bold; margin: 5px 0; }

        /* Print Settings */
        @media print {
            .no-print { display: none; } /* Hide buttons when printing */
        }
    </style>
</head>
<body onload="window.print()">

    <div class="no-print" style="margin-bottom: 20px;">
        <a href="{{ route('dashboard') }}" style="text-decoration: none; background: #333; color: white; padding: 8px 15px; border-radius: 4px;">← Back to Dashboard</a>
    </div>

    <div class="header">
        <h1>Nicey Burger Junction</h1>
        <p>Official Inventory Report</p>
        <p>Generated on: {{ date('F d, Y - h:i A') }}</p>
        <p>Generated by: {{ Auth::user()->email }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 50px;">ID</th>
                <th>Product Name</th>
                <th>Category</th>
                <th style="text-align: right;">Price</th>
                <th style="text-align: right;">Stock</th>
                <th style="text-align: right;">Total Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->product_name ?? $product->name }}</td>
                    <td>{{ $product->type }}</td>
                    <td style="text-align: right;">₱{{ number_format($product->price, 2) }}</td>
                    <td style="text-align: right;">{{ $product->quantity }}</td>
                    <td style="text-align: right;">
                        ₱{{ number_format($product->price * $product->quantity, 2) }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="totals">
        <p>Total Items in Stock: {{ number_format($totalStock) }}</p>
        <p>Total Inventory Value: ₱{{ number_format($totalValue, 2) }}</p>
    </div>

    <br>
    <br>

    <div style="margin-top: 50px; display: flex; justify-content: space-between;">
        <div style="border-top: 1px solid black; width: 200px; padding-top: 5px;">Prepared By</div>
        <div style="border-top: 1px solid black; width: 200px; padding-top: 5px;">Approved By</div>
    </div>

</body>
</html>